CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.payment (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sales numeric(19, 2),
    points numeric(19, 2),
    additional_item jsonb,
    customer_id varchar(255),
    datetime timestamptz,
    CONSTRAINT payment_pkey PRIMARY KEY (id)
);